### ISSUE TITLE
Name of the mod is an issue

### ISSUE THREAD

**Issue by RenatoLopes771** [joe7575/tubelib2#1]
A

**Comment by joe7575** [comment]
This is a joke, right?
But anyhow, this is a library. 
1) I can't change the name without breaking compatibility to other mods.
2) This library is not visible to players
So, who cares?

**Comment by underlineGalaxy** [comment]
@joe7575 its not a joke.

As an example, Viper's server use the stock mod with the same name.

Well if it is unfixable I suppose there's nothing to be done. Still, it's not a "joke issue."
