### ISSUE TITLE
Documentation for integrating with other mods

### ISSUE THREAD

**Issue by roobre** [joe7575/tubelib2#16]
Hey there!

Once again I'd like to start thanking your for all the work you put on these super cool mods!

I'm trying to see if I can integrate the drawers mod with techage's tube system. Conceptually I think this should be simple: Drawers mod have a block called a controller, which has a single-slot inventory. I think adding the ability for tubes to push items to that inventory would be enough for integrating. Glancing at the drawer's code, I can see a small snippet which seem to achieve integration with the pipeworks mod:

https://github.com/minetest-mods/drawers/blob/0ea57687b3bb39cd80d6100691a64c2166bbdc1d/lua/controller.lua#L472-L491

I _think_ then it should be easy, and hopefully similar, to do the same thing with tubelib: Setting some properties to true so tubes recognize this block as something they can push to, and implementing some handlers on the drawer controller to react to items being pushed to it.

Unfortunately I haven't been able to find examples or documentation about what properties/handlers a block needs to have for tubelib to be able to interact with them. Is this something documented, or exemplified somewhere?

Thanks a lot in advance!

**Comment by joe7575** [comment]
Cool, I would like to see techage support for drawers.
https://github.com/joe7575/techage/blob/master/basic_machines/foreign_nodes.lua shows some adaptions to other nodes like the `default:chest`:
```lua
techage.register_node({"default:chest", "default:chest_open"}, {
	on_inv_request = function(pos, in_dir, access_type)
		local meta = minetest.get_meta(pos)
		return meta:get_inventory(), "main"
	end,
	on_pull_item = function(pos, in_dir, num)
		local meta = minetest.get_meta(pos)
		local inv = meta:get_inventory()
		return techage.get_items(pos, inv, "main", num)
	end,
	on_push_item = function(pos, in_dir, stack)
		local meta = minetest.get_meta(pos)
		local inv = meta:get_inventory()
		return techage.put_items(inv, "main", stack)
	end,
	on_unpull_item = function(pos, in_dir, stack)
		local meta = minetest.get_meta(pos)
		local inv = meta:get_inventory()
		return techage.put_items(inv, "main", stack)
	end,
})
``` 
This is the easiest way of integration.
The implementation of `default:chest_locked` shows how to protect the access. 
Let me know, if you need further info.

**Comment by Niklp09** [comment]
@roobre https://github.com/minetest-mods/drawers/pull/74
